--CRIANDO BLOCO ANONIMO
--AULA  https://youtu.be/jZ19rKuRsSk


select * from EMPLOYEES;


DECLARE 
 
    V_NM_FUNCIONARIO HR.EMPLOYEES.FIRST_NAME%TYPE; 
     
BEGIN 
    --CRIAÇÃO DE UM CURSOR EXPLICITO 
    SELECT FIRST_NAME 
    INTO V_NM_FUNCIONARIO -- JOGANDO DENTRO DE UMA VARIAVEL O FIRST_NAME 
    FROM HR.EMPLOYEES 
    WHERE EMPLOYEE_ID = 102; 
     
     
    IF V_NM_FUNCIONARIO <> 'LEX' THEN 
        DBMS_OUTPUT.PUT_LINE('NOME: ' || V_NM_FUNCIONARIO); -- PACKAGE INTERNA DO ORACLE ONDE POSSUI VARIAS PROCEDURES, PARA CHAMADA DA MESMA PRECISA SER DESSA FORMA 
    ELSE 
        DBMS_OUTPUT.PUT_LINE('NOT OK'); 
    END IF; 
 
END;




/*BLOCO ANONIMO PARA TRAZER TODOS OS FUNCIONARIOS QUE GANHAM MAIS DE 12008*/


DECLARE 
 
    V_SL_FUNCIONARIO HR.EMPLOYEES.SALARY%TYPE; 
     
BEGIN 
    SELECT FIRST_NAME || LAST_NAME, SALARY 
    INTO V_SL_FUNCIONARIO -- INTO RETORNA MUITOS VALORES ENTRÃO PRECISO DECLARAR UM LOOP
    FROM HR.EMPLOYEES 
     
    IF V_SL_FUNCIONARIO > 12008 THEN 
        DBMS_OUTPUT.PUT_LINE('SALARIO ALTO: ' || V_SL_FUNCIONARIO); 
    ELSE 
        DBMS_OUTPUT.PUT_LINE('SALARIO PADRÃO PARA O CARGO: ' || V_SL_FUNCIONARIO); 
    END IF; 
END;



     
/*PARA A SITUAÇÃO ACIMA É NECESSARIO UM LOOP*/

DECLARE 
 
    V_SL_FUNCIONARIO HR.EMPLOYEES.SALARY%TYPE; 
    V_NMF_FUNCIONARIO HR.EMPLOYEES.FIRST_NAME%TYPE; 
     
BEGIN 
    FOR R IN( 
        SELECT FIRST_NAME, SALARY 
        FROM HR.EMPLOYEES 
        WHERE SALARY > 12008 
    ) 
    LOOP 
     DBMS_OUTPUT.PUT_LINE('SALARIO ALTO: ' || R.FIRST_NAME || R.SALARY); 
    END LOOP; 
END; 
