use universidade_u;


CREATE TABLE BASE_DADOS_GUIA_MEDICO(
    SITUACAO VARCHAR(50) NOT NULL,
    COD_PRESTADOR VARCHAR(50) NOT NULL,
    NM_PRESTADOR VARCHAR(255) NOT NULL,
    NM_FANTASIA VARCHAR(255) NOT NULL,
    CEP NUMERIC(8) NOT NULL,
    ESPECIALIDADE VARCHAR(255) NOT NULL,
    TIP_PRESTADOR VARCHAR(60) NOT NULL,
    CODIGO_OPERADORA float(5) NOT NULL,
    HOSPITAL_CLINICO_MEDICO float(8) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    TIPO_DE_CONTATO VARCHAR(150) NOT NULL,
    OUTROS_CELULAR VARCHAR(255) NOT NULL,
    TIPO_PESSOA VARCHAR(255) NOT NULL,
    CNPJ_CPF float(14) NOT NULL,
    CD_PRESTADOR_ENDERECO float(5),
    CD_TIPO_ENDERECO float(4),
    DS_TIPO_ENDERECO VARCHAR(100),
    TP_LOGADOURO VARCHAR(20),
    DS_ENDERECO VARCHAR(255),
    NR_ENDERECO VARCHAR(255),
    DS_COMPLEMENTO VARCHAR(255),
    DS_BAIRRO VARCHAR(100),
    CD_MUNICIPIO float(6),
    DS_MUNICIPIO VARCHAR(255) NOT NULL,
    CD_UF VARCHAR(2) NOT NULL,
    SN_PRINCIPAL enum('S', 'N'),
    SN_DIVULGA enum('S', 'N'),
    DT_INATIVACAO DATE
);

drop table BASE_DADOS_GUIA_MEDICO;

select * from BASE_DADOS_GUIA_MEDICO